# Generated by Django 3.2.5 on 2021-07-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeleaf',
            name='files',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='treeleaf',
            name='image',
            field=models.URLField(),
        ),
    ]
