# Generated by Django 3.2.5 on 2021-07-09 08:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210709_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeleaf',
            name='files',
            field=models.FileField(upload_to=main.models.getcurrentusername),
        ),
        migrations.AlterField(
            model_name='treeleaf',
            name='image',
            field=models.ImageField(upload_to=main.models.getcurrentusername),
        ),
    ]
